### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by netsrotr** [GenuineChannels/GenuineChannels#5]
Currently it is not possible to start a server side TCP listener on a IPv6 address, like "::1". In case we provide the "interface" parameter to the GenuineTcpChannel ctor via properties HashTable using the mentioned interface, it fails to parse the port internally (because the ":" is used within the addressa itself, not only as a port delimiter) within function call to (TcpConnectionManager:: line 2320):

 `string interfaceAddress = GenuineUtility.SplitToHostAndPort(endPoint, out port);`

I don't know if this is the only line of code that would be have to change to enable IPv6 support. 
How about a version 2.6 with IPv6 support enabled?

**Comment by yallie** [comment]
Hi, 

>I don't know if this is the only line of code that would be have to change to enable IPv6 support.

I'm sorry I have no idea :)
But I'd be very surprised if it boiled down to this single line.

>How about a version 2.6 with IPv6 support enabled?

I'm adding some minor improvements/bugfixes on [this forked copy of the GC project](https://github.com/zyanfx/GenuineChannels), and I'm going to push my changes here once I clean things up, but I'm afraid I don't have much time for major improvements such as IPv6 support. Although I'd be happy if you give it a try yourself and submit a PR :)

Thanks, Alex

**Comment by netsrotr** [comment]
I [forked](https://github.com/netsrotr/GenuineChannels) your project, please have a look for the changes. You might like to adopt the new test base class to your existing tests. Please have a look at the TODO comment within the code, we might have to discuss this as an additional feature (TCP port sharing) and how to enable it

**Comment by yallie** [comment]
Hello @netsrotr ,

Sorry for being inactive, I'm currently on vacation!
I have no objections to the common base class for the unit tests, seems quite reasonable.
Can you make a pull request to [zyanfx/GC](https://github.com/zyanfx/GenuineChannels)?

Regarding TCP sharing — I think it's a cool feature, but it should be opt-in and
not enabled by default. Otherwise, it'd be a breaking change. Please don't add
the TCP port sharing support for now, let's split it into a separate issue.

Thanks for your effort! — Alex

**Comment by yallie** [comment]
https://github.com/zyanfx/GenuineChannels/pull/6

**Comment by yallie** [comment]
Thanks @netsrotr for implementing the feature!
Nuget package v2.5.9.10 is just published.
